#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Hawaii

# Short bio or description (displayed in the header)
description: The QtQuick and Wayland system

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: hawaiios
  flickr: 
  github: hawaii-desktop
  google-plus: 106410682256187719404
  google-plus-community: 114894812299360329015
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: hawaiiinux
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: UC9clGPyuP23DyI8EgQRq87Q
  slack: hawaiios

# Your disqus shortname, entering this will enable commenting on posts
disqus: hawaiios

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-33602199-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://hawaiios.org

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Pagination
# Set the number of posts per page
paginate: 4

# Authors
authors:
  plfiorini:
    first_name: "Pier Luigi"
    last_name: "Fiorini"
    gravatar: "63d069a6a87ca59f2cfbf270fa16abbf"
    web: "http://plfiorini.blogspot.com/"
    twitter: "plfiorini"
    github: "plfiorini"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: <!-- more -->

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed

# HTML compression options
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-contentblocks
  #- jekyll-minifier
  - jekyll-paginate

# Exclude certain resources from minimization
jekyll-minifier:
  exclude: 'atom.xml'

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
